### PR TITLE
keep /bin/sh as parent process

### PR DESCRIPTION
**Pull request by valvin1**
related to #105 

daemon.php is not managing its children but sh could do it.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Thanks for fixing it :-)

plz change it here https://github.com/friendica/docker/blob/master/docker-cron.sh#L10
and call `./update.sh` (https://github.com/friendica/docker/blob/master/update.sh)

Never change the docker images directly :)
https://github.com/friendica/docker/blob/master/README-MAINTENANCE.md#version-directories

**Comment by valvin1** [comment]
oh i wasn't aware of that process ;-) It was looking strange to me to have to change n times the same file.
`update.sh` changes more than just my change (version). Hope it'll be ok.

**Comment by nupplaphil** [comment]
That's fine. It's part of the update process to check the newest depenend libraries and add it :). Currently it won't even be possible to not update it, since travis checks if the executed update command results to the same hash as the commited one :)

**Comment by valvin1** [comment]
@nupplaphil thank you for merging :)

does it mean `2019.12` image is now fix with this update if I pull it again?

**Comment by nupplaphil** [comment]
nope, I've to add a PR to the offical images as well .. I'll do it today evening :-)

**Comment by MrPetovan** [comment]
Just making sure.

**Comment by nupplaphil** [comment]
@valvin1 keep an eye on https://github.com/docker-library/official-images/pull/7573 :)

**Pull request merged**
