### PR TITLE
Switch to Debian Buster

### PR DESCRIPTION
**Pull request by nupplaphil**
As suggested here https://github.com/docker-library/official-images/pull/8341#issuecomment-658308684 by @yosifkit , I now upgrade the Friendica debian images to buster.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Can you please look into the test failures?

**Comment by nupplaphil** [comment]
Jep, I've to switch to another smtp solution since ssmtp is no more available :-) I'll now use msmtp but it has different config settings so there is some investigation needed

**Comment by MrPetovan** [comment]
Any more changes planned?

**Comment by nupplaphil** [comment]
Nope, I'm done and it's working now :-) tested the mail config at my node and worked.

**Comment by MrPetovan** [comment]
Awesome!

**Pull request merged**
