### PR TITLE
docker-77 Deduplicate dependencies

### LINKED ISSUE #77: Deduplicate dependencies
Some dependencies and extensions are already provided by the base image, so there's no need to add them again:

https://github.com/friendica/docker/blob/af1aa857f6867ee394a07d7f93a2c06091836dc9/2019.06/fpm-alpine/Dockerfile#L55-L67
https://github.com/docker-library/php/blob/d367f7fb843c23f265f732256bb196b160523cd2/7.3/alpine3.10/fpm/Dockerfile#L134-L145

### PR DESCRIPTION
**Pull request by nupplaphil**
- remove curl
- remove mbstring

Fixes #77 

@j0wi I checked the Dockerfile and "just" found these two. Any other redundancies?
```bash
        pdo \
        pdo_mysql \
        xml \
        gd \
        zip \
        opcache \
        posix \
        ctype \
        json \
        iconv \
        pcntl \
```

### CODE REVIEW

**Comment by J0WI** [comment]
`ctype`, `iconv`, `pdo`, `posix` and `xml` can be removed too. The removal of `curl` may also make the `libssl-dev` and `openssl` dependency obsolete.

**Comment by nupplaphil** [comment]
Thx, I trink now I got all of them :)
Is there an overview about what php extensions are already shipped with the php docker image? If not maybe you can add it, so one doesn't has to search in the source :)

**Comment by J0WI** [comment]
There are some more duplicates:
You should use `$PHPIZE_DEPS` instead of adding `make`, `autoconf`, `g++` etc. manually.
On Debian `libfreetype6` is already installed by `libfreetype6-dev`.
On Alpine `libcurl` is already present, `rsync` is already added as `entrypoint.sh` dependency and I think `bzip2` is not used at all. `freetype` can be removed due `freetype-dev` and `libpng` is added twice, but is already a dependency of `libpng-dev`.

>  Is there an overview about what php extensions are already shipped with the php docker image? If not maybe you can add it, so one doesn't has to search in the source :)

I'm not aware of any. The Docker image uses the upstream defaults with the [exceptions listed in the source](https://github.com/docker-library/php/blob/d367f7fb843c23f265f732256bb196b160523cd2/7.3/alpine3.10/fpm/Dockerfile#L128-L145). This also depends on the used version.

**Comment by nupplaphil** [comment]
And again :D .. Now I learned a lot too :-)

**Comment by nupplaphil** [comment]
@mrpetovan plz merge if it fits for you :) thx :)

**Pull request merged**
