### PR TITLE
Revert "Force docker upgrade at startup"

### PR DESCRIPTION
**Pull request by elrido**
This reverts the force (`-f` flag) of the database upgrade on startup,
as per the discussion in https://github.com/friendica/friendica/issues/10375#issuecomment-855604924 and https://github.com/friendica/docker/pull/137#issuecomment-857431269

### CODE REVIEW

**Comment by annando** [comment]
I just had got a look in he code. Currently I have the feeling as if at some point in the past there had been a change in the `-f` parameter. Before doing anything with this PR please let me check the code once more. Possibly `-f` is safe and I was wrong.

**Comment by MrPetovan** [comment]
What is the final word? `-f` or not?

**Comment by annando** [comment]
I had a look at git. @nupplaphil had done the changes two years ago in PR https://github.com/friendica/friendica/pull/6740. From this time on the `force` parameter is safe. I even commented on that PR ...

P.S.: If someone meets my memory, please tell it to return to me :-)

**Comment by MrPetovan** [comment]
Closing here then since the removal of the parameter sounds unwarranted.

**Pull request closed without merging**
