### PR TITLE
Change cron behaviour & supervisor support

### PR DESCRIPTION
**Pull request by nupplaphil**
Currently, `bin/worker.php` is automatically forking "n" (standard 3) sub-processes with parameter "no_cron".

That's good if you have a single crontab/container and you start forking the background process from this unique point.

But if you want to run the frontend and the cron processes in one container, you need supervisor.
And supervisor doesn't like background forking (issue #12 ). I found a description what kind of subprocesses supervisor supports at http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses

Therefore I added a parameter to the `cron.sh` where you can put the "no_cron" argument for the worker.php in case of supervisor. supervisor itself is creating multiple processes (`numprocs`) to scale the cronjobs.

### CODE REVIEW

**Comment by annando** [comment]
I'm currently unsure about this. The maximum number of workers can be defined in the admin console. Additionally the "fast lane" would always fork additional workers if low priority processes are blocking the current workers and there are high priority processes waiting.

You really don't want to try the daemon? :smile:

**Comment by nupplaphil** [comment]
Hm .. I got your point why you are unsure:
- Overruling the max number of workers setting of the admin setting
- possible issue with "fast lane" mechanism

I will give the daemon a try, but I have to look if it's usable for docker:
- has to run in foreground-mode (because otherwise the docker will stop the container if there is no "execution point" left)
- needs to be fit for `supervisor` (see the link I posted first)

**Comment by annando** [comment]
At some point in history I hope I will be able to understand some basics of docker. I never used it, I only know that is is some method to run programs. Currently I don't know any background, not even how docker really works. And of course I do not know any docker specific wording.

So I must confess that I don't know, if the daemon can be used with docker at all.

**Comment by nupplaphil** [comment]
The most important parts:
- **image** = like a "virtual machine" but with all dependencies, libs and binaries you need for a given use case (a service or "just" an executable).
- **container** = a concrete build of an image which you can use (starting the service or execute a command inside an image)
- **entrypoint** = A script or something similar which will get called anytime you use the container -
 like auto-updates, auto-install, it's like an injection and it also defines what happens to all commands you execute (see CMD)
- **CMD** = the command which is the "default" command at the end when you start the container (you can override it if you like) - like "apache2 -DFOREGROUND"

This CMD is my problem :-). Because it's like executing something in a shell. So if - f.e. - you start a service and it forks itself in the background, the CMD will get finished too and therefore **stops the container**

**Comment by nupplaphil** [comment]
YES!! Tanks @annando ! That's what I thought about! I'm currently at a (great) festival and will add it next weak.

I'm therefore closing this PR and will return hopefully with a great daemon usage :)

**Pull request closed without merging**
