### PR TITLE
Hotfix 2020.07-1

### PR DESCRIPTION
**Pull request by nupplaphil**
See https://github.com/friendica/friendica/releases/tag/2020.07-1
- Removes 2020.03 because of security issue
- points "old" 2020.07 releases to the hotfix zip as well

### CODE REVIEW

**Comment by nupplaphil** [comment]
arg .. because of "2020.07-dev" is lower than "2020.07", the logic will see "2020.07-1" lower than "2020.07" as well .. I've to fix it first because the docker upgrade would brick ..

**Comment by nupplaphil** [comment]
ok the logic of #130 works for the hotfix as well now :-)

**Comment by nupplaphil** [comment]
@tobiasd can you please provide a "2020.07-1" archive for the addons as well? otherwise I would have to add additional logic (uneven versions core vs. addon :-) )

**Comment by MrPetovan** [comment]
Tests are failing.

**Comment by nupplaphil** [comment]
Yep because they're searching a 2020.07-1 addon archive :-)

**Comment by tobiasd** [comment]
I've copied the 2020.07-addons file to 2020.07-1.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
