### PR TITLE
Update to PHP 8.2

### PR DESCRIPTION
**Pull request by ne20002**
Update to PHP 8.2
Update Debian template to bookworm

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
I assume you tested these changes locally?

**Comment by ne20002** [comment]
> I assume you tested these changes locally?

Roughly. It's running on my local system but I make very little use of many features, just use Friendica with Tusky.
It might be a good idea to postpone merging until the release 24.06 is out. Just to give it more time for testing.

**Comment by ne20002** [comment]
~~Ok, there is a problem. I focused on the new release and didn't see that updating the template and php version will also apply these changes to the already existing releases. This is not what is expected and I believe this is something that needs to be changed in the update script.~~
While the update.sh is applying changes to the templates also to the Dockerfiles of previous versions this is no problem as long as we don't inlcude this into the changes to the manifest file for the docker library.

**Comment by ne20002** [comment]
Hi @MrPetovan 
I ran into problems downloading the sources from files.friendi.ca. The request times out and this happens on multiple devices and on Github actions as well. Even in a browser opening files.friendi.ca so I assume its on that side. Any idea?

**Comment by nupplaphil** [comment]
@ne20002 - Why is this PR not ready? Seems ready to me, so I started `./update.sh` and no we let's have a look if it can get built :-)

And I think it's a good idea to switch it for all images. Because every admin can choose when to pull the newest image and restart it. We don't need any exceptions for any release-tag from my point of view

**Comment by ne20002** [comment]
We postponed the PR because we didn't want to take too much risks shortly before the last release.
I used it locally but as stated above, this is not proper testing.
I don't think this update is risky as php 8.1 to 8.2 is a minor upgrade.
Updating the base to bookworm should not cause trouble.

If we merge it I can do an update of the manifest for just the dev images. That should give the update a proper testing until the next release.
We also can push an update to the current release version if no problems pops up with the dev version. No need to rush here.

**Pull request merged**
