### PR TITLE
Fixing DNS_PTR & DNS_CNAME problems in docker environments.

### PR DESCRIPTION
**Pull request by nupplaphil**
Fix for #6 

In docker environments, the DNS_PTR and DNS_CNAME doesn't work very well. So I made a patch to remove them from `include/dba.php` ;-)

### CODE REVIEW

**Comment by MrPetovan** [comment]
Shouldn't this be fixed in the Friendica codebase itself? I don't think we need `dns_get_record()` to connect to the database.

**Comment by nupplaphil** [comment]
Hm.. you're right.

But I thought I found a reason why it is necessary in the dba.php ..
That's why I made this workaround. I have to search in the closed issues of Friendica, maybe I found out what it was ..

**Comment by MrPetovan** [comment]
I believe it was because we had no fail safe if the connection failed. This has been fixed since. In the meantime: https://github.com/friendica/friendica/issues/5116

**Comment by nupplaphil** [comment]
So do we add this Workaround until you fixed it in Friendica?

Because otherwise the install wizard doesn't work.

**Comment by MrPetovan** [comment]
No, this here is pretty dirty, I'd rather not add it at all.

**Comment by tobiasd** [comment]
If possible the fix should be added to the current RC so that the upcoming stable release benefits from it.

**Comment by MrPetovan** [comment]
There you go.

**Comment by nupplaphil** [comment]
thank you @MrPetovan for the quick fix :-)

So I close this PR and I will just publish the 2018.05-rc for docker, because the other releases are currently pretty useless, aren't they? From what I know the 2018.05 will get released next Weekend :-).

**Pull request closed without merging**
